[tool.poetry]
name = "anchorpy"
version = "0.4.1"
description = "The Python Anchor client."
readme = "README.md"
repository = "https://github.com/kevinheavey/anchorpy"
documentation = "https://kevinheavey.github.io/anchorpy/"
authors = ["kevinheavey <kevinheavey123@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
construct-typing = "^0.5.1"
solana = "^0.18.2"
sumtypes = "^0.1a5"
inflection = "^0.5.1"
borsh-construct = "^0.1.0"
websockets = "^10.0"
toolz = "^0.11.2"
jsonrpcclient = "^4.0.1"
zstandard = "^0.16.0"
pytest-xprocess = "^0.18.1"
apischema={ git = "https://github.com/snuderl/apischema.git", rev = "62d07cc02b7a291fc3ad1206d025630eb4e30889" }

[tool.poetry.dev-dependencies]
pytest = "^5.2"
wemake-python-styleguide = "^0.15.3"
mypy = "^0.910"
black = "^21.7b0"
pydocstyle = "^6.1.1"
isort = "^5.9.3"
pytest-asyncio = "^0.15.1"
mkdocs-material = "^7.3.3"
bump2version = "^1.0.1"
pyserum = "^0.5.0-alpha.0"
mkdocstrings = "^0.16.2"

[tool.poetry.plugins.pytest11]
pytest_anchorpy = "anchorpy.pytest_plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
